### ISSUE TITLE
createOrAccumulate breaks when exceeding ChunkSize on primary key unique violation

### ISSUE THREAD

**Issue by MatOwczarek** [lapaliv/laravel-bulk-upsert#48]
Hi!
It seems as if `createOrAccumulate` breaks when exceeding ChunkSize on primary key violation. My test setup: 
```
$userBulk = User::bulk()->chunk(50)->uniqueBy(['uuid']);
try {
    for ($i = 1; $i <= 200; $i++) {
        // Same when creating new model and giving model's instance to createOrAccumulate
        $user = [
            'uuid' => Str::uuid(),
            'name' => 'test' . $i,
            'email' => 'test@test.test' . $i,
        ];
        $userBulk->createOrAccumulate([$user]);
    }
}
catch (Throwable $e) {
    dd($i, $e);
}
```
this breaks on 51st iteration with `SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "users_pkey" DETAIL: Key (id)=(82) already exists.`

Laravel 9.52.16
Laravel-bulk-upsert 2.2.3

**Comment by lapaliv** [comment]
Hi. 

Thank you for your issue. I have fixed it. Please use the `2.2.4` version
