### ISSUE TITLE
updateOrAccumulate does not remove previous row from bulk's storage when chunkSize is set to 1

### ISSUE THREAD

**Issue by MatOwczarek** [lapaliv/laravel-bulk-upsert#49]
Hi (again 😅)!
It seems like `updateOrAccumulate` breaks sometimes when chunkSize is set to 1. When looking at Bulk instance it looks like previous rows are not removed from storage array. 
Test case on 11 updates to the same model, chunk size = 1:
![image](https://github.com/lapaliv/laravel-bulk-upsert/assets/68372661/92e7f3ea-842b-4a20-bf5a-ab1944f2ed65)
Test case on 11 updates to the same model, chunk size = 2:
![image](https://github.com/lapaliv/laravel-bulk-upsert/assets/68372661/77e4ac02-0bab-4898-8cdf-39646ec29c30)

Laravel 9.52.16
Laravel-bulk-upsert 2.2.3

**Comment by lapaliv** [comment]
This problem is fixed. Please use the `2.2.4` version
